tap "fabianishere/personal"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "ack"
brew "antigen"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "openssl@1.1"
brew "readline"
brew "unixodbc"
brew "asdf"
brew "awscli"
brew "bash"
brew "curl"
brew "gettext", link: true
brew "git"
brew "gnupg"
brew "grep"
brew "jid"
brew "jq"
brew "krew"
brew "python"
brew "libxslt"
brew "mas"
brew "moreutils"
brew "openssh"
brew "rancher-cli"
brew "rke"
brew "screen"
brew "starship"
brew "tree"
brew "unzip"
brew "watch"
brew "wget"
brew "yq"
brew "zsh"
brew "fabianishere/personal/pam_reattach"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "1password"
cask "1password-cli"
cask "aerial"
cask "alfred"
cask "avibrazil-rdm"
cask "cakebrew"
cask "discord"
cask "docker"
cask "dropbox"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-firacode-nerd-font"
cask "font-firacode-nerd-font-mono"
cask "font-firamono-nerd-font"
cask "font-firamono-nerd-font-mono"
cask "font-hasklig"
cask "font-hasklig-nerd-font"
cask "font-iosevka"
cask "font-iosevka-nerd-font"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-sourcecodepro-nerd-font"
cask "font-sourcecodepro-nerd-font-mono"
cask "google-backup-and-sync"
cask "google-chat"
cask "google-cloud-sdk"
cask "iterm2"
cask "messenger"
cask "microsoft-teams"
cask "pock"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "rocket"
cask "sequel-pro"
cask "spotify"
cask "tunnelblick"
cask "vagrant"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "Aware", id: 1082170746
mas "BetterSnapTool", id: 417375580
mas "FuzzyTime", id: 950297057
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "KubeContext", id: 1438838068
mas "Numbers", id: 409203825
mas "OmniFocus", id: 1346203938
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Reeder", id: 1449412482
mas "Slack", id: 803453959
mas "Twitter", id: 1482454543
