tap "adoptopenjdk/openjdk"
tap "beamly/tap"
tap "derailed/k9s"
tap "drewsonne/tap"
tap "fabianishere/personal"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "nektos/tap"
brew "ack"
brew "antigen"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "openssl@1.1"
brew "readline"
brew "unixodbc"
brew "asdf"
brew "gettext"
brew "awscli"
brew "bash"
brew "cmatrix"
brew "curl"
brew "fx"
brew "git"
brew "gnupg"
brew "graphviz"
brew "grep"
brew "gtk+3"
brew "hub"
brew "jid"
brew "jq"
brew "krew"
brew "libxml2"
brew "libxslt"
brew "mas"
brew "minikube"
brew "moreutils"
brew "octant"
brew "openjdk"
brew "openssh"
brew "postgresql"
brew "pygobject3"
brew "qemu"
brew "rancher-cli"
brew "rke"
brew "sbt"
brew "screen"
brew "socat"
brew "sops"
brew "starship"
brew "stern"
brew "tig"
brew "tree"
brew "unzip"
brew "vault"
brew "watch"
brew "wget"
brew "x11vnc"
brew "yq"
brew "zsh"
brew "beamly/tap/go-gocd"
brew "derailed/k9s/k9s"
brew "fabianishere/personal/pam_reattach"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "nektos/tap/act"
cask "1password"
cask "1password-cli"
cask "adoptopenjdk8"
cask "aerial"
cask "alfred"
cask "apache-directory-studio"
cask "avibrazil-rdm"
cask "cakebrew"
cask "discord"
cask "docker"
cask "dropbox"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-firacode-nerd-font"
cask "font-firacode-nerd-font-mono"
cask "font-firamono-nerd-font"
cask "font-firamono-nerd-font-mono"
cask "font-hasklig"
cask "font-hasklig-nerd-font"
cask "font-iosevka"
cask "font-iosevka-nerd-font"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-sourcecodepro-nerd-font"
cask "font-sourcecodepro-nerd-font-mono"
cask "gitify"
cask "google-backup-and-sync"
cask "google-chat"
cask "google-cloud-sdk"
cask "intellij-idea-ce"
cask "iterm2"
cask "java"
cask "messenger"
cask "michaelvillar-timer"
cask "microsoft-teams"
cask "monitorcontrol"
cask "nightowl"
cask "pock"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "rocket"
cask "sequel-pro"
cask "spotify"
cask "tunnelblick"
cask "vagrant"
cask "visual-studio-code"
cask "webpquicklook"
cask "xquartz"
mas "Amphetamine", id: 937984704
mas "Aware", id: 1082170746
mas "BetterSnapTool", id: 417375580
mas "FuzzyTime", id: 950297057
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "KubeContext", id: 1438838068
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "OmniFocus", id: 1346203938
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Reeder", id: 1449412482
mas "Slack", id: 803453959
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
